<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFrameworks>net6.0-windows;net7.0-windows;net8.0-windows;net9.0-windows;net472</TargetFrameworks>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
        <Authors>Josué Clément</Authors>
        <Copyright>Copyright © 2025 Josué Clément</Copyright>
        <PackageId>MdiWpf</PackageId>
        <Title>Material design icons for WPF</Title>
        <Version>2.0.0</Version>
        <Description>WPF vector icon library using MaterialDesign open source icons</Description>
        <PackageTags>wpf icons materialdesign</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageProjectUrl>https://github.com/josueclement/MdiWpf</PackageProjectUrl>
        <RepositoryUrl>https://github.com/josueclement/MdiWpf</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <!-- Readme for the NuGet package -->
    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\LICENSE.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="svg\*.svg" />
      <EmbeddedResource Include="svg\*.svg" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    </ItemGroup>

</Project>
